### ISSUE TITLE
Missing Packages from Repo

### ISSUE THREAD

**Issue by tbsteinb** [jianyunt/ChocolateyGet#11]
It looks like some packages are not being found in the repo. For example Vivaldi. If I run `choco search vivaldi` I see that the package is available and can install it. If I run `packagemanager -providername chocolateyget -name vivaldi` it tells me no match was found. This is only the case for some packages though. I was able to find and install kdevelop just fine.

**Comment by ethanbergstrom** [comment]
I'm not seeing this even with the current provider:
```powershell
PS C:\Users\ethan> find-package vivaldi -providername chocolateyget

Name                           Version          Source           Summary
----                           -------          ------           -------
Vivaldi                        3.0.1874.38      https://www.c...
```
