### ISSUE TITLE
Hash for package 'ChocolateyGet' does not match hash provided from the server.

### ISSUE THREAD

**Issue by tlsalex** [jianyunt/ChocolateyGet#13]
**when I installed chocolateyget , it showed me some "error". I want to know whether it will be a critical issue or not . any advise ?**

> Hash for package 'ChocolateyGet' does not match hash provided from the server.

bellow is the full output.

[xx.xx.xx.xx]: PS C:\> Install-PackageProvider ChocolateyGet -verbose
VERBOSE: Using the provider 'Bootstrap' for searching packages.
VERBOSE: Finding the package 'Bootstrap::FindPackage' 'ChocolateyGet','','','''.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ChocolateyGet'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'ChocolateyGet'.
VERBOSE: Performing the operation "Install Package" on target "Package 'ChocolateyGet' version '1.0.0.1' from 'PSGallery'.".
VERBOSE: The specified module will be installed in 'C:\Program Files\WindowsPowerShell\Modules'.
VERBOSE: The specified Location is 'NuGet' and PackageManagementProvider is 'NuGet'.
VERBOSE: Downloading module 'ChocolateyGet' with version '1.0.0.1' from the repository 'https://www.powershellgallery.com/api/v2'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='ChocolateyGet'' for ''.
VERBOSE: InstallPackage' - name='ChocolateyGet', version='1.0.0.1',destination='C:\Users\tlsadmin\AppData\Local\Temp\2015507138'
VERBOSE: DownloadPackage' - name='ChocolateyGet', version='1.0.0.1',destination='C:\Users\tlsadmin\AppData\Local\Temp\2015507138\ChocolateyGet\C
hocolateyGet.nupkg', uri='https://www.powershellgallery.com/api/v2/package/ChocolateyGet/1.0.0.1'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/ChocolateyGet/1.0.0.1'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/ChocolateyGet/1.0.0.1'.
VERBOSE: Completed downloading 'ChocolateyGet'.
VERBOSE: Hash for package 'ChocolateyGet' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='ChocolateyGet', version='1.0.0.1',destination='C:\Users\tlsadmin\AppData\Local\Temp\2015507138'
VERBOSE: Catalog file 'ChocolateyGet.cat' is not found in the contents of the module 'ChocolateyGet' being installed.
VERBOSE: Module 'ChocolateyGet' was installed successfully to path 'C:\Program Files\WindowsPowerShell\Modules\ChocolateyGet\1.0.0.1'.

**Comment by jianyunt** [comment]
I never see this error while downloading  the ChocolateyGet.  In fact` ChocolateyGet.cat` never exists in the ChocolateyGet package. @alerickson, any breaking changes in PowerShellGet or PackageManagement for checking .cat file recently?

**Comment by jianyunt** [comment]
@tlsalex, for the work around, you can use PowerShellGet to download the package
``` PowerSHell
Find-module ChocolateyGet -verbose | install-module -force -verbose -SkipPublisherCheck
Import-PackageProvider ChocolateyGet
Get-PackageProvider
```

**Comment by alerickson** [comment]
No changes in either PSGet or PackageManagement that relate to checking .cat files
