### ISSUE TITLE
Choco.exe doesn't install automatically due to TLS 1.2 changes

### ISSUE THREAD

**Issue by ethanbergstrom** [jianyunt/ChocolateyGet#16]
Looks like @ferventcoder broke ChocolateyGet's ability to automatically install choco.exe by [removing support for TLS 1.1 and below](https://chocolatey.org/blog/remove-support-for-old-tls-versions). The provider needs to tell PowerShell that its OK to use TLS 1.2.

Example of how to fix: ethanbergstrom@93b0ec126aa68c00f2e1a881f9283dc7a86a9cf0

**Comment by ferventcoder** [comment]
👍 We didn't purposely break abilities here - we needed to move to more secure cryptos over the web and 2020 seemed like a great time to make that happen.
