### ISSUE TITLE
Unable to find any Chocolatey packages

### ISSUE THREAD

**Issue by severidaniele** [jianyunt/ChocolateyGet#4]
Hi, I have installed ChocolateyGet as per instructions and verified that it is imported. However, when trying to find a package I get these Warnings/Errors.

```
PS C:\windows\system32> find-package -ProviderName ChocolateyGet -name  nodejs
WARNING: User declined to install Chocolatey.
WARNING: Method invocation failed because [PsRequest_proxy_21] does not contain a method named 'ShouldContinue'.
find-package : No match was found for the specified search criteria and package name 'nodejs'.
At line:1 char:1
+ find-package -ProviderName ChocolateyGet -name  nodejs
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.FindPackage:FindPackage) [Find-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.FindPackage
```

Is there a problem with ChocolateyGet or am I doing something wrong?

Thanks

**Comment by stuncloud** [comment]
Try `-Force` parameter.
It went ok for me.

**Comment by jianyunt** [comment]
@etabeta888 It is likely you are using old version of PackageManagement which did not support ShouldContinue.  To upgrade PackageManagement and PowerShellGet, you can do something like:

install-module -Name PowerShellGet -force 

this will upgrade both PowerShellGet and PackageManagement. Then relaunch PowerShell console.

However if you are using Win10 anniversary, or Server 2016, or WMF 5.0 RTM or WMF 5.1 Preview, no PowerShellGet  upgrade is needed. You should not encounter the error.
