### ISSUE TITLE
Uninstall without dependencies

### ISSUE THREAD

**Issue by jberezanski** [jianyunt/ChocolateyGet#40]
Currently, when uninstalling a package with ChocolateyGet, the `--remove-dependencies` switch is always passed to choco.exe.

In many cases this is not desired behavior. The dependencies removal function of Choco is rather simplistic and does not account for the difference between packages installed automatically as dependency and packages explicitly installed by the user. As such, too many packages may get uninstalled.

Consider these packages:
`keepass-plugin-winhello` depends on `keepass`
`keepass` depends on `keepass.install`

If a user installs KeePass, then (possibly some time later) installs the WinHello plugin for it, and finally decides that (s)he does not want to use the plugin after all, uninstalling `keepass-plugin-winhello` will:
- (when done using choco.exe directly)
  - (with no additional parameters, default behavior) remove the plugin only, keeping KeePass installed
  - (with `--remove-dependencies` passed explicitly) remove both the plugin and the entire KeePass application
- (when done using ChocolateyGet) remove the entire KeePass application, with no way of uninstalling the plugin only.

I believe that ChocolateyGet, at the very least, should provide a way to opt out of dependency uninstallation (and perhaps it should even be the default behavior, to align with choco.exe defaults).

**Comment by ethanbergstrom** [comment]
Thanks, this is a good example. I tried this myself by explicitly installing `keepass` first, then installing `keepass-plugin-winhello`, and you're correct that uninstalling `keepass-plugin-winhello` removes the whole dependency chain, which is not the intended behavior. 

This will need to be an upstream change in Foil and exposed in ChocolateyGet.
