### ISSUE TITLE
Updating to newest choco (0.11.1)

### ISSUE THREAD

**Issue by jberezanski** [jianyunt/ChocolateyGet#41]
ChocolateyGet currently installs a rather old version of Choco (0.10.13), as a workaround for issues present in 0.10.14-15 (and fixed in 0.10.16 beta).

Now that choco 0.11.1 has been released, can ChocolateyGet be updated to install that version (or simply the newest version)?

**Comment by ethanbergstrom** [comment]
Thanks for the suggestion!

I'm not sure I want to make the jump to always take the latest version, in case @ferventcoder and co. introduce a breaking change in choco's behavior or output format. However, bumping the version installed by default shouldn't be a big deal.
