### ISSUE TITLE
Find-Package : A parameter cannot be found that matches parameter name 'Provider'.

### ISSUE THREAD

**Issue by sassdawe** [jianyunt/ChocolateyGet#46]
Following the example from the README.md `Find-Package curl -RequiredVersion latest -Provider ChocolateyGet` generates the error:

> ```Find-Package : A parameter cannot be found that matches parameter name 'Provider'.
> At line:1 char:43
> + Find-Package curl -RequiredVersion latest -Provider ChocolateyGet
> +                                           ~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [Find-Package], ParameterBindingException
>     + FullyQualifiedErrorId : NamedParameterNotFound,Find-Package```

And dropping the `-Provide` parameter generates two other errors:

> ```You cannot call a method on a null-valued expression.
> At C:\Program Files\WindowsPowerShell\Modules\ChocolateyGet\4.0.0\private\Find-ChocoPackage.ps1:68 char:6
> +     if ($minimumVersion -Or $maximumVersion -Or $options.ContainsKey( ...
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
>     + FullyQualifiedErrorId : InvokeMethodOnNull
> 
> New-SoftwareIdentity : The term 'New-SoftwareIdentity' is not recognized as the name of a cmdlet, function, script file, 
> or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At C:\Program Files\WindowsPowerShell\Modules\ChocolateyGet\4.0.0\private\ConvertTo-SoftwareIdentity.ps1:29 char:4
> +             New-SoftwareIdentity @swid
> +             ~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (New-SoftwareIdentity:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException```

**Comment by ethanbergstrom** [comment]
@sassdawe you didn't happen to run `Import-Module` on ChocolateyGet, did you?

Unlike most PowerShell modules, PackageManagement providers shouldn't be used with the `-Module`  cmdlets, but with the `-PackageProvider` cmdlets (despite what PSGallery says 😜 ). If it's already installed with `Install-Module`, it should still work, but definitely do **not** use `Import-Module` with it. 

Please see https://github.com/ethanbergstrom/Chocolatier/issues/5#issuecomment-590522980 for a similar type of issue as what you're seeing.

**Comment by sassdawe** [comment]
I ran this from a brand-new session, started with `-noprofile` nothing was imported

![image](https://user-images.githubusercontent.com/10754765/142764889-0b9f5889-eed1-4234-b025-86eb16125110.png)

**Comment by sassdawe** [comment]
I am starting to understand it, I think... 

Am I supposed to `Import-PackageProvider` every time before I can use `Find-Package`
![image](https://user-images.githubusercontent.com/10754765/142765277-4e613c48-98a6-4695-ae02-28aaf4e2a9ee.png)

**Comment by ethanbergstrom** [comment]
I don't have to run `Import-PackageProvider` every time I use it, so long as I specify the provider name in `Find-Package` for example. The two are interchangeable. 

See https://docs.microsoft.com/en-us/powershell/module/packagemanagement/install-packageprovider for more information on example usage.

If you're still seeing weirdness, I would recommend using `Uninstall-Module` and reinstall it with `Install-PackageProvider`.
