### ISSUE TITLE
Section Keep packages up to date: the "latest" keyword is not needed

### ISSUE THREAD

**Issue by sgryphon** [jianyunt/ChocolateyGet#49]
The section on Section Keep packages up to date says "PackageManagement/OneGet is it doesn't allow for updating installed packages", but that is not correct. If you install the latest it just updates.

This works similar to Linux e.g. sudo apt-get install <package>, updates to the latest package.

If you leave off the version parameters (-RequiredVersion, -MinimumVersion, -MaximumVersion) then by default it means latest version.

i.e. -RequiredVersion latest is the same as not specifying a version at all.

**Comment by ethanbergstrom** [comment]
Hey @sgryphon ,

You're correct that if provided to `Install-Package` there's no real difference in behavior. 

The `latest` keyword logic is really intended for use with `Get-Package` to determine if an upgrade is available and be paired with `Install-Package` to create 'upgrade' behavior without having to constantly change the version number passed to it. 

The primary use case for that was with PowerShell DSC for configuration management purposes. DSC will only run `Install-Package` if `Get-Package` doesn't return anything to maintain idempotency. 

See OneGet/oneget#6 for an example of where the '_OneGet doesn't allow updates_' narrative comes from, though that's not the forum I've heard that feedback about OneGet. 

I'll take a look at your PR to see if there's a better way to clarify that, yes, you can upgrade a package with just `Install-Package` without the `latest` keyword while still also trying to the need of those looking for an `Update-Package`-esque behavior.

**Comment by sgryphon** [comment]
Well, it's not quite idempotency anyway, because you want a different output, for the command, based on external state. 

Ignoring things like outputting logs, etc (things generally aren't fully idempotent), then if you run `Install-Package -Name curl -Provider ChocolateyGet`, then 10 minutes later run it again, you get the same resulting state (i.e. the second Install does nothing, as it is already up to date). (The log outputs are different).

If you ran it 3 days later, when a new version was released, then `Install-Package -Name curl -Provider ChocolateyGet` will do the update if it exists (or do nothing if it does not). There is no real need to check with a Get first. DSC just needs to always run the command.

The problem is that Get-Package, but itself, gets the current installed version, but doesn't tell you if it needs to be updated; Find-Package tells you the latest, but not what is installed.   So, you kind of want a Test-Package command that will compare the two and determine if a new one is needed ... which isn't really necessary as Install-Package determines that internally anyway.

I think, reading the "doesn't allow updates" what is actually wanted is something similar to the "upgrade" command in apt-get. In apt-get, the "update" command actually just updates the manifests of which versions are available, then the upgrade command automatically loops through all installed packages, sees if they are at the latest version, and if not, installs the latest version.

You could do similar with a simple loop, like the one I have in the PR, where you do a global Get-Package (or a per-provider), then loop through each one and call Find-Package... filter for ones that don't match, and call Install-Package:

```
Get-Package | Select Name, Version, ProviderName, @{l="LatestVersion";e={(Find-Package $_.Name -Provider $_.ProviderName).Version}} | ? { $_.Version -ne $_.LatestVersion } | % { Install-Package $_.Name -Provider $_.ProviderName }
```

So yeah, a single command to do this for your (update all relevant packages) would be good, but not really relevant for updating individual packages.
