### ISSUE TITLE
Packages with no checksum appear to fail

### ISSUE THREAD

**Issue by CMCDragonkai** [jianyunt/ChocolateyGet#6]
Try this:

```
Install-Package -name 'gifcam' -providername 'chocolateyget' -force
```

Vs

```
choco install gifcam
```

It appears that there's another prompt asking whether to proceed if there's no checksum. In this case gifcam is not installed if attempted to be installed via Install-Package.

**Comment by ethanbergstrom** [comment]
Seems to work now, even with the current provider. Might have been a transitive issue with the package a few years ago.
