### ISSUE TITLE
Proxy Support 

### ISSUE THREAD

**Issue by sebastianzolg** [jianyunt/ChocolateyGet#8]
When using ChocolateyGet behind a proxy server, in some situations its not working. 
While choco.exe can be easily configured to use a proxy [https://github.com/chocolatey/choco/wiki/Proxy-Settings-for-Chocolatey#explicit-proxy-settings](url), the ChocolateyGet Module can't. 

**Function Install-ChocoBinaries** uses Invoke-WebRequest at some point, which doesn't work behind a proxy server per default. While this is not a big deal when using ChocolateyGet in normal PS1 Scripts, as we can set the proxy using **[system.net.webrequest]::defaultwebproxy** globally, this is not possible when using ChocolateyGet within a PowerShell DSC Configuration as LCM has no option to set a proxy, as far as I know. 

That means, there is no way to make it work within a DSC Configuration behind a proxy. 

**Recommendation**: Allow the ChocolateyGet Module to receive AdditionalParameters, so it can be set using the same approach as other package providers, e.g. NuGet [https://github.com/PowerShell/PackageManagementProviderResource/blob/master/Examples/Sample_Install_Package_Using_NuGet.ps1](url) > Note the AdditionalParameters Dictionary, that can be passed. 

thanks

**Comment by sebastianzolg** [comment]
What do you think ?

**Comment by jianyunt** [comment]
@BenAffleckIsBatman  thanks for your suggestions. Your are right, the PackageManagement DSC takes additionalparameters that can be passed down to its providers. And the providers need to implement to take these parameters in install-package, save-package etc. In the ChocolateyGet case, are you thinking to add proxyurl, proxy url, proxyCredential?

Also I am open to take PR. Do you have any bandwidth to do so?

**Comment by sebastianzolg** [comment]
@jianyunt I would love to help. Put that on my list. I struggled with a good debug setup for these situations. I asked on [StackOverflow](https://stackoverflow.com/questions/44204271/how-to-debug-powershell-package-provider-e-g-chocolateyget-in-vscode) a while ago. Could you answer it and tell something about the best way to debug & unit test? Specially how to construct the PackageManagement object passed down to the implementation. Any advise ?

**Comment by jianyunt** [comment]
Just posted it in StackOverflow. I created it a while back using ISE.
Also there are some information that may be useful to you in the wiki in oneget.org

**Comment by ethanbergstrom** [comment]
@sebastianzolg my pull request (#15) introduces default behavior that invokes Chocolatey's native API that's bundled into the provider, so it no longer tries to install / upgrade choco.exe unless API support is expressly disabled or used with PowerShell 7+, which should alleviate the need to pass in proxy settings for downloading Choco.exe through DSC arguments.
