### ISSUE TITLE
Search problem

### ISSUE THREAD

**Issue by sixtead** [jianyunt/ChocolateyGet#9]
Using `Find-Package -Name "chrome" -ProviderName ChocolateyGet` finds nothing and gives error:
```powershell
Find-Package : Совпадения для указанных условий поиска и имени пакета "chrome" не найдены. Чтобы просмотреть все доступные зарегистрированные источники пакетов, используйте командлет Get-PackageSource.
строка:1 знак:1
+ Find-Package -Name "chrome" -ProviderName ChocolateyGet
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.FindPackage:FindPackage) [Find-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.FindPackage
```

While `Find-Package -Name "chrome" -ProviderName Chocolatey` finds all packages with "chrome" in it's names.

**Comment by jianyunt** [comment]
@ferventcoder,  any ideas what's going on for the packages in https://chocolatey.org/? I cannot find or install.

``` PowerShell
PS C:\test> choco search nodejs --id-starts-with
Chocolatey v0.10.8
0 packages found.
PS C:\test> choco search 7zip
Chocolatey v0.10.8
0 packages found.
PS C:\test> choco list chrome*
Chocolatey v0.10.8
0 packages found.
PS C:\test> clist *chrome*
Chocolatey v0.10.8
0 packages found.

PS C:\> choco install 7zip
Chocolatey v0.10.8
Installing the following packages:
7zip
By installing you accept licenses for the packages.
7zip not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the packa
 Version: ""
 Source(s): "http://wanuget/bootstrap/nuget"

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

**Comment by ferventcoder** [comment]
@jianyunt looks like maybe the source for you.

~~~
Source(s): "http://wanuget/bootstrap/nuget"
~~~

**Comment by jianyunt** [comment]
@ferventcoder no luck with the source. what's the syntax?
``` PowerShell
PS C:\Program Files\7-Zip> choco search 7zip -s "'http://wanuget/bootstrap/nuget'"
Chocolatey v0.10.8
0 packages found.
PS C:\Program Files\7-Zip> choco search nodejs -s "http://wanuget/bootstrap/nuget"
Chocolatey v0.10.8
0 packages found.
```

**Comment by ferventcoder** [comment]
I don't know that source, I'm thinking it might be something local for you?

**Comment by ferventcoder** [comment]
You have the syntax right, but if you don't have those packages on the source you are using, it won't turn up results. The community repo is at https://chocolatey.org/api/v2

**Comment by jianyunt** [comment]
@sixtead it looks like working now
Find-Package -Name GoogleChrome  -ProviderName ChocolateyGet
or
Find-Package -Name  *Chrome  -ProviderName ChocolateyGet

``` PowerShell
PS Azure:\> Find-Package -Name GoogleChrome  -ProviderName ChocolateyGet

Name                           Version          Source           Summary
----                           -------          ------           -------
GoogleChrome                   63.0.3239.132    https://www.c...


Azure:\
PS Azure:\> Find-Package -Name  *Chrome  -ProviderName ChocolateyGet

Name                           Version          Source           Summary
----                           -------          ------           -------
GoogleChrome                   63.0.3239.132    https://www.c...
google-chrome-x64              47.0.2526.81     https://www.c...
adblockpluschrome              1.12.4           https://www.c...
...
```

**Comment by sixtead** [comment]
Search works fine. I mean, searching packages with choco works without asterisk (`choco list chrome`), searching packages with PowerShell using Chocolatey package provider (`Find-Package -Name chrome -ProviderName Chocolatey`) works without asterisk. But when you search package with ChocolateyGet provider (`Find-Package -Name chrome -ProviderName ChocolateyGet`) it gives you error.

Maybe it should behave like choco itself (without asterisk)?

And is there a way not ot throw error message and print something like "The package 'chrome' cannot be found, try using `Find-Package -Name *chrome -ProviderName ChocolateyGet` instead"?

**Comment by jianyunt** [comment]
Got it. Thanks @sixtead. 
I made the ChocolateyGet  search operation as "exact match" so that it works just like PowerShellGet (find-module) for http://PowerShellGallery.com.  
As ChocolateyGet  has over 320 thousands downloads already I cannot remove 'exact match' behavior otherwise I break someone else. Maybe I can add optional argument later.
To remove the exact match behavior, you may comment out everything in the [Test-name](https://github.com/jianyunt/ChocolateyGet/blob/master/ChocolateyGet.psm1#L636) and replace them "return true". ChocolateyGet.psm1 file can be found in your module installed folder.

**Comment by sixtead** [comment]
Ok. Thanks for explaration. I think issue can be closed.

**Comment by jianyunt** [comment]
Thanks closed the issue.
